### ISSUE TITLE
add versioning

### ISSUE THREAD

**Issue by michaldengusiak** [HoareLea/SAM#135]
**Describe the solution you'd like**

when we have old nodes, would be good to have version so we can know what version it is based on...
**Additional context**

![image](https://user-images.githubusercontent.com/26113670/86462505-9e908d80-bd23-11ea-9659-d7f3f0d573f7.png)

**Comment by michaldengusiak** [comment]
in Ladybug it is used like
![image](https://user-images.githubusercontent.com/26113670/87127870-96d26b00-c286-11ea-8407-1e0c4bbd24b6.png)

**Comment by michaldengusiak** [comment]
ok version added

@ZiolkowskiJakub  @willhl  we could propose some ideas here

![image](https://user-images.githubusercontent.com/26113670/87133669-8ecaf900-c28f-11ea-901e-5517de192d4e.png)
currently this is automated via here but we could adjust to better system..
![image](https://user-images.githubusercontent.com/26113670/87133743-aace9a80-c28f-11ea-880b-5cc17ab42064.png)

**Comment by willhl** [comment]
Are the ladybug versions updated automatically?

We could use the assembly version, and there are tools to automate this, from memory when I've tried this before it can cause issues with assembly loading if the version of the dependent assembly isn't the same as the one that was used to build it. This might only apply to major version number changes, increments to patch number might be fine.

For the build service, we could get it to inject the build number into the code when it's built? this doesn't necessarily solve the issue because it won't work where the assemblies are built locally.

**Comment by willhl** [comment]
I think we need to get semantic versioning up an running, or at lest inject the version numbers at build, so for releases the users will have consistency across the version shown in GH and the version they installed.

**Comment by michaldengusiak** [comment]
ok right now we implemented version
that refers to deploy the version

![image](https://user-images.githubusercontent.com/26113670/91309602-b0813080-e7a8-11ea-91f7-350cf34726a6.png)
